### ISSUE TITLE
App crashes during app start

### ISSUE THREAD

**Issue by obranies** [LoadingByte/cinecred#1]
App downloaded: v1.4.0

System details: 

MacBook Pro 16 (2019)
2,3 GHz 8-Core Intel Core i9
AMD Radeon Pro 5500M 4 GB
Intel UHD Graphics 630 1536 MB
16 GB 2667 MHz DDR4
MacOS Ventura Version 13.3.1 (a) (22E772610a)

<img width="286" alt="CleanShot 2023-05-09 at 17 34 54@2x" src="https://github.com/LoadingByte/cinecred/assets/8235717/27e6c2bf-553c-4d2a-a172-930a7867594f">

App crashes immediately after start. Only system info modal shown (screenshot attached)

**Comment by LoadingByte** [comment]
Thanks for the report!

This is in fact a security warning in disguise; as far as I know, it only appears when extracting the app from the TAR.GZ download, so I assume you went that route?

The issue is rather easy to solve. I've collected instructions at the bottom of this webpage: https://cinecred.com/security-warnings/ (*macOS → When Launching the App / Beim Starten der App*)

Alternatively, you can also download the PKG and install Cinecred that way.

**Comment by obranies** [comment]
Actually it was the PKG (cinecred-1.4.0-x86_64.pkg) that I used for installing it. :-/

**Comment by LoadingByte** [comment]
Oh, that's strange. I've never heard that happen.

To help me identify the issue, can you launch the app after running the following command in the terminal?
```
xattr -d com.apple.quarantine /Applications/Cinecred.app
```

**Comment by LoadingByte** [comment]
I just tested installing Cinecred 1.4.1 using the PKG installer on a **freshly installed** Intel Mac with Ventura. I encountered the regular security warning when opening the PKG (cf. https://cinecred.com/security-warnings/#when-launching-the-installer), but once the app has been installed, it properly launches without the "damaged app" warning you reported.

So I'm even more confused now regarding what's going on. Does running the command from my previous post help? Did you maybe change some security-related settings on your Mac? Is it maybe configured to only permit apps from the App Store (a setting under "Privacy & Security")?

I'd really like to get to the bottom of this to both help you and other people who might stumble across the same issue.

**Comment by LoadingByte** [comment]
It appears that sometimes, right-clicking the app and choosing "Open" can solve the problem you encountered; c.f. https://www.reddit.com/r/editors/comments/13ekb5r/comment/jjrbdsm/.

**Comment by obranies** [comment]
Hi, 
ok, tested the command in Terminal. Got an "permission denied" response. Hence tested running it as sudo. Still "permission denied". 
I tested the right-click-open case and that worked. It did show the same error modal as before but this time with an open option. After opening it this way and going through a few options of the app it now starts as expected (as in: using spotlight or dock entries). 
Taking another look at the error message I wonder if it may be an metadata issue?! (See "Diese Datei wurde an einem unbekannten Datum geladen")

Hopethishelps
