### ISSUE TITLE
[Question] How to fix the image on the side and have a scrolling text?

### ISSUE THREAD

**Issue by Nikronic** [LoadingByte/cinecred#10]
Hi, 

Firstly, I wanted to say such amazing work. It is amazing, and I really loved it so far.

And to the question, I was wondering if it is possible (the title). Here is picture of the structure, but image is only fixed and the text is scrolling?

Bests,
Nikan

**Comment by LoadingByte** [comment]
Did I correctly understand that you'd like to have scrolling text next to a non-moving image? Currently, that's unfortunately not possible, but it's on my ToDo list. So for the time being, you'd have to superimpose the image onto the exported credits using video editing software.

**Comment by Nikronic** [comment]
Hi, thank you for the response.
Yes exactly. Sorry for not attaching the image (apparently network issue and never double-checked it). 
It is absolutely fine, for some unknown reason I assumed it would be easy (of course it's not!) and just though asking. 

Again, thanks for this awesome tool.

PS: I close this issue as it resolved in my opinion.

Bests
