### ISSUE TITLE
[Feature] Stroke Text Box

### ISSUE THREAD

**Issue by mezhgano** [LoadingByte/cinecred#12]
Sometimes it is needed to stroke person name in credits, for example in case of death, like this:

![credits_rip_stroke](https://github.com/user-attachments/assets/048bf2cf-4f83-41a3-bdc7-97564c93bdca)

I'm inspected `Letter Styles` and only find options to **Strikethrough** and **Underline**, is it possible to implement something to achieve stroke around text, like in screenshot? With possibility to round edges.

I'm tried to play with **Fill**, using 2 fills at the same time (black and white), but it is impossible to adjust fill size, so no way to construct white rectangle, or i didn't find a way to do it...

**Comment by LoadingByte** [comment]
Yes, it's possible! Here's what you can get:

![Credits with boxes around names](https://github.com/user-attachments/assets/d0daac00-3f5e-4bdf-b27d-40b4bdbe225b)

For this, the letter style needs to additional layers: an "inner box" and an "outer box". Here are their settings; I've grayed out all irrelevant ones:

![Letter style configuration](https://github.com/user-attachments/assets/38dde5cd-98e4-4c89-83c4-e4bc7c85ec6d)

The inner box doesn't have a color, and it only serves to be subtracted from the outer box (via "Clear Around Layers"). The widening of the inner box controls the padding inside the box. The widening of the outer box controls the line thickness. And finally, both the inner and outer corner styles and radii can be configured; in this case, I've set them to round corners.

**Comment by mezhgano** [comment]
Ah, i forgot about **advanced** button, here we go...
Thanks, mark as solved.
