### ISSUE TITLE
Will there be more language support?

### ISSUE THREAD

**Issue by zixzaxlad** [LoadingByte/cinecred#2]
This software looks truly amazing!
Unfortunately, Chinese characters do not seem to be supported. Will there be Unicode support for Chinese/Japanese/Korean? Unicode should be the most universal solution for Chinese characters/Kanji (though I'm not certain, just did a quick search). 
Is there any chance we can get Chinese character support?
Great software nonetheless, I really appreciate it.

**Comment by LoadingByte** [comment]
All writing systems are supported, even right-to-left text is correctly handled (and even when mixing LTR and RTL sections). However, you need a font that supports the characters you use. For example, the fonts that are shipped with Cinecred don't support Chinese characters. However, when selecting a font that does (e.g., Noto Sans CJK SC), Chinese text is correctly rendered:

![image](https://github.com/LoadingByte/cinecred/assets/2351649/d16b3c05-c50c-48fb-9004-76a6adf0df26)

**Comment by zixzaxlad** [comment]
My bad, I totally forgot to check the font thing. Making ending credits in Excel used to be a real pain in the ass. It's a lifesaver I would say. By the way, I might be able to help with Chinese localization if needed. The only issue is I couldn't find an editable localization file. Skimming on my phone so I may miss something.


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Felix Mujkanovic ***@***.***>
发送时间: Tuesday, May 23, 2023 12:45:54 AM
收件人: LoadingByte/cinecred ***@***.***>
抄送: zixzaxlad ***@***.***>; Author ***@***.***>
主题: Re: [LoadingByte/cinecred] Will there be more language support? (Issue #2)


All writing systems are supported, even right-to-left text is correctly handled (and even when mixing LTR and RTL sections). However, you need a font that supports the characters you use. For example, the fonts that are shipped with Cinecred don't support Chinese characters. However, when selecting a font that does (e.g., Noto Sans CJK SC), Chinese text is correctly rendered:

[image]<https://user-images.githubusercontent.com/2351649/239975120-d16b3c05-c50c-48fb-9004-76a6adf0df26.png>

―

**Comment by LoadingByte** [comment]
Funnily enough, another user actually already translated Cinecred into Chinese, and this will ship in the next release. But thanks a lot for your offer!

**Comment by zixzaxlad** [comment]
That's awesome! I really appreciate your speedy reply. Hope I didn't trouble you with this kind of issue that I should have double checked on my own. Thanks again for your understanding and quick assistance!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Felix Mujkanovic ***@***.***>
发送时间: Tuesday, May 23, 2023 1:43:51 AM
收件人: LoadingByte/cinecred ***@***.***>
抄送: zixzaxlad ***@***.***>; Author ***@***.***>
主题: Re: [LoadingByte/cinecred] Will there be more language support? (Issue #2)


Funnily enough, another user actually already translated Cinecred into Chinese, and this will ship in the next release. But thanks a lot for your offer!

―

**Comment by LoadingByte** [comment]
Just a quick thought... would you maybe be willing to double-check the translation? As I can't read Chinese myself, I'd be very grateful for someone to make sure that the translation is indeed accurate.

If you are open for this, just email me at felix *At* cinecred *Dot* com, and we'll talk about the details.

**Comment by zixzaxlad** [comment]
a small issue related to Chinese
Whenever I render a file with a Chinese character the software will crash.

**Comment by LoadingByte** [comment]
I just tried it and it doesn't crash for me. Could you maybe elaborate on what exactly you did, and, if possible, include the credits and styling files from your project folder?

**Comment by zixzaxlad** [comment]
I simply set the file name to Chinese, add to the render queue then hit render. It crashes when I hit the render button. I've sent my project file and a crash screen recording to your email.
________________________________
发件人: Felix Mujkanovic ***@***.***>
发送时间: 2023年5月26日 20:50
收件人: LoadingByte/cinecred ***@***.***>
抄送: zixzaxlad ***@***.***>; Author ***@***.***>
主题: Re: [LoadingByte/cinecred] Will there be more language support? (Issue #2)


I just tried it and it doesn't crash for me. Could you maybe elaborate on what exactly you did, and, if possible, include the credits and styling files from your project folder?

―

**Comment by LoadingByte** [comment]
Alright, I managed to reproduce the crash—it happens on Windows only, it seems—when rendering a video whose filename contains non-ASCII characters. This was because for some reason, strings were not encoded as UTF-8 but something else when being passed to FFmpeg, but only on Windows.

I'm now forcing UTF-8 encoding, and this has fixed the issue. The fix will ship in the next release; until then, you have to use ASCII characters only as a workaround when exporting video files. Thanks for your report!
