### ISSUE TITLE
HD and 25 frames

### ISSUE THREAD

**Issue by jreykdal** [LoadingByte/cinecred#3]
Hi,
Any chance of implementing other dimensions and frame rates? HD and 25 fps for example?

Would make TV work easier.

Regards,
JR

**Comment by LoadingByte** [comment]
It's in fact already possible to enter arbitrary resolutions and frame rates in the "Global Styling" settings :)

![Choosing a custom resolution and frame rate](https://github.com/LoadingByte/cinecred/assets/2351649/a57b65ad-7014-414a-9e36-70276cc4878d)

**Comment by jreykdal** [comment]
Ah! Thank you!
