### ISSUE TITLE
Export in 25p and 50i

### ISSUE THREAD

**Issue by Momomio** [LoadingByte/cinecred#4]
Hi,

Is it possible to export in 25p or 50i or is it only on a 24 base for now ?

**Comment by LoadingByte** [comment]
Yes, that's possible. You can set the project's frame rate to 25 in the "Global Styling" settings:

![Choosing a custom frame rate](https://github.com/LoadingByte/cinecred/assets/2351649/a57b65ad-7014-414a-9e36-70276cc4878d)

If you need interlaced output, you can enable that in the delivery dialog (provided you selected a format that supports it, e.g., ProRes):

![Selecting interlaced output](https://github.com/LoadingByte/cinecred/assets/2351649/614dff09-b6ab-4e01-b067-48602bcc0215)

**Comment by Momomio** [comment]
Oh yes, indeed, my bad ^^
Thank you !
