### ISSUE TITLE
Issue with the Cinecred YUM packages : Conflict with filesystem due to /usr/bin

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [LoadingByte/cinecred#5]
On Fedora 38, after adding the Yum Repository, the package has issue installing due to an apparent conflict with the filesystem, reserving the /usr/bin filepath. It seems something wrong with the packaging path…

**Comment by LoadingByte** [comment]
You're right. I've now fixed the issue for version 1.5.0, which will ship soon. Until then, you can just install Cinecred manually from the tarball.
