### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [LoadingByte/cinecred#7]
Can WTFPL be avoided for the website?
There are only two other projects using it on Hosted Weblate.

WTFPL proliferates the amount of licenses by being redundant to a lot of other options.
Also it complicates communicating that "everything is GPLv3+".

It can be changed in
https://hosted.weblate.org/settings/cinecred/website/
if need be.

**Comment by LoadingByte** [comment]
Agreed, changed it to GPLv3 only to match the other components.

**Comment by LoadingByte** [comment]
Good point as well! I wasn't aware that licensing under GPLv3+ also permits changing to AGPLv3 later on; I always thought it only included a potential GPLv4.

I'll talk with the translators who have contributed so far and change the license to GPLv3+ if they accept.

**Comment by LoadingByte** [comment]
Actually, I'm not sure whether "or later" really permits redistributing the code under the AGPLv3. For example, [this official FAQ entry](https://www.gnu.org/licenses/license-list.html#AGPLv3.0) states that:

> you cannot take code released under the GNU AGPL and convey or modify it however you like under the terms of GPLv3, **or vice versa**.

However, apart from this, I can't find any more information online. Do you maybe have some trustworthy sources that support the claim?

Of course, it's questionable whether changing to the AGPLv3 really holds merit for a software like Cinecred, which would be very cumbersome to use over the network due to its local nature. The only nice thing would be the possibility to include libraries licensed under the AGPLv3.

**Comment by comradekingu** [comment]
@LoadingByte 
GPLv2 isn't compatible with v3
https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility
It runs into the "No" category of
https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
However there is a specific provision between v3 and AGPLv3
https://www.gnu.org/licenses/gpl-faq.html#AGPLGPL

AFAIK going GPLv3+ to AGPLv3+ for the whole thing is possible, but not AGPLv3+ to GPLv3+.

So I guess at least _there is some more flexibility in being able to go GPLv4_ down the road if that turns out to be good.

I think going from GPLv3-only over to something AGPLv4 means it would have to be adopted in full,
which constitutes "a work" for which the entire license applies.
Doing it over time with the clause in a dual-licensing way would maybe technically work(?), but it would have to replace everything.

The same goes for setting up an untainted clean proxy program to migrate code, because the licenses are inherently incompatible, so I don't think there could be any backwards-compatibility(?)

**Comment by LoadingByte** [comment]
>Each of these licenses explicitly permits linking with code under the other license. You can always link GPLv3-covered modules with AGPLv3-covered modules, and vice versa. That is true regardless of whether some of the modules are libraries.

Huh, that's pretty interesting. Does this mean that it's allowed to ship a library licensed under the AGPLv3 (like Ghostscript) in software licensed under the GPLv3 (like Cinecred). From what I've read, the compound then becomes AGPLv3 while Cinecred's source remains GPLv3, whatever that might mean.

Anyway, I've received confirmation from contributors that going GPLv3+ is fine, so I'll relicense. Seems like that offers the most flexibility we can get without implementing a CLA.
